#!/bin/bash
# Runs a CPLEX execution with mod/dat files, saves the results and send an email

if [ $# -lt 3 ]; then
	echo "You must provide 2 input files and session ID"
	exit
fi

ID=$1
SESSION_PATH="/home/sposApp/sessions/$ID/"
FILEMOD=$SESSION_PATH$3
FILEDAT=$SESSION_PATH$2

if ! { [ -e $FILEMODE ] && [ -e $FILEDAT ]; }; then
	echo "Files must exist"
	exit
fi

SendEmail() {
	echo "done"
}

RESULTS_NAME="results.txt"
RESULTS_FILE=$SESSION_PATH$RESULTS_NAME

oplrun $FILEMOD $FILEDAT > $RESULTS_FILE && SendEmail