#!/bin/bash
# Runs a CPLEX execution with mod/dat files, saves the results and send an email

if [ $# -lt 5 ]; then
	echo "You must provide 2 input files and session ID, email and key"
	exit
fi

ID=$1
KEY=$2
EMAIL=$3
SESSION_PATH="/home/sposApp/sessions/$ID/"
FILEMOD=$SESSION_PATH$5
FILEDAT=$SESSION_PATH$4

if ! { [ -e $FILEMODE ] && [ -e $FILEDAT ]; }; then
	echo "Files must exist"
	exit
fi

SendEmail() {
	echo "Execution Complete. Sending email...."
	echo -e "Dear user, \n We are glad to announce that your execution with ID $ID has finished succesfully. \n Please go to our website and log in with the ID and password of your session to get the results. \n\n Session ID: $ID \nSession Key: $KEY \n\n Thanks for using our service. Best regards." | mail -s "SPOS - Execution complete" $EMAIL
}

RESULTS_NAME="results.txt"
RESULTS_FILE=$SESSION_PATH$RESULTS_NAME

echo "StartTime: $(date +'%s')" > $RESULTS_FILE && oplrun $FILEMOD $FILEDAT >> $RESULTS_FILE && echo -e "\nFinishTime: $(date +'%s')" >> $RESULTS_FILE  && sshpass -p 'sposudl15' scp -i /root/.ssh/id_rsa $RESULTS_FILE root@192.168.101.113:$RESULTS_FILE && SendEmail
