#!/bin/bash
# Runs a CPLEX execution with mps or lp files, saves the results and send an email

if [ $# -lt 4 ]; then
	echo "You must provide one input file, session ID, key and an email"
	exit
fi

ID=$1
KEY=$2
EMAIL=$3
SESSION_PATH="/home/sposApp/sessions/$ID/"
FILE=$SESSION_PATH$4
DURATION=$5
FRONTENDIP=$6
SUCCESS=0


if ! [[ -e $FILE ]]; then
	echo "File must exist"
	exit
fi

SendEmail() {
	echo "Execution Complete. Sending email...."
	echo -e "Dear user, \n We are glad to announce that your execution with ID $ID has finished succesfully. \n Please go to our website and log in with the ID and password of your session to get the results. \n\n Session ID: $ID \n Session Key: $KEY \n\n Thanks for using our service. Best regards." | mail -s "SPOS - Execution complete" $EMAIL
}

SendResults() {
	END_TIME=$(date +'%s')
	CPU_DATA=cpuData.txt
	MEM_DATA=memData.txt
	collectData $START_TIME $END_TIME &&
	echo "Sending results..." &&
	eval "$(ssh-agent -s)" &&
	echo "SSH Agent started" &&
	sshpass -p "S10s6oi2" scp -i /root/.ssh/id_rsa $RESULTS_FILE root@$FRONTENDIP:$RESULTS_FILE &&
	sshpass -p "S10s6oi2" scp -i /root/.ssh/id_rsa /var/lib/munin/results/$CPU_DATA root@$FRONTENDIP:$SESSION_PATH$CPU_DATA &&
	sshpass -p "S10s6oi2" scp -i /root/.ssh/id_rsa /var/lib/munin/results/$MEM_DATA root@$FRONTENDIP:$SESSION_PATH$MEM_DATA &&
	echo "Results sent!" &&
	SUCCESS=1 &&
    SendEmail
}

RunExecution() {
	if [ $DURATION -eq -1 ]; then
		cplex -c "read $FILE" "optimize" "display solution variables -" "quit" >> $RESULTS_FILE
	else
		cplex -c "set clocktype 1" "set timelimit $DURATION" "read $FILE" "optimize" "display solution variables -" "quit" >> $RESULTS_FILE
	fi
}

RESULTS_NAME="results.txt"
RESULTS_FILE=$SESSION_PATH$RESULTS_NAME
START_TIME=$(date +'%s')

echo "StartTime: $(date +'%s')" > $RESULTS_FILE && RunExecution && echo -e "\nFinishTime: $(date +'%s')" >> $RESULTS_FILE && SendResults

if [ $SUCCESS -eq 0 ]; then
        if [ -e $RESULTS_FILE ]; then
                sshpass -p "S10s6oi2" scp -i /root/.ssh/id_rsa $RESULTS_FILE root@$FRONTENDIP:$RESULTS_FILE
        fi
fi
