#!/bin/bash
# Runs a CPLEX execution with mod/dat files, saves the results and send an email

if [ $# -lt 2 ]; then
	echo "You must provide 2 input files"
	exit
elif ! { [ -e $1 ] && [ -e $2 ]; }; then
	echo "Files must exist"
	exit
fi

SendEmail() {
	echo "done"
}

SESSION_PATH=$(dirname "$1")
RESULTS_NAME="results.txt"
RESULTS_FILE=$SESSION_PATH$RESULTS_NAME

oplrun $1 $2 > $RESULTS_FILE && SendEmail